# Generated by Django 3.1.7 on 2021-05-06 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img_works', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('thumb_img', models.ImageField(default='default_thumb.jpg', upload_to='pictures')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img_works', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('thumb_img', models.ImageField(default='default_thumb.jpg', upload_to='pictures')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='dreamnode_social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img_works', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('thumb_img', models.ImageField(default='default_thumb.jpg', upload_to='pictures')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='our_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img_works', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('thumb_img', models.ImageField(default='default_thumb.jpg', upload_to='pictures')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_content', models.TextField()),
                ('content', models.TextField(default='There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.')),
                ('content_main', models.TextField(default='There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.')),
                ('heading_1', models.CharField(default='Heading', max_length=100)),
                ('heading_2', models.CharField(default='reaching for the stars', max_length=100)),
                ('image_main', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('image_other', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
