# Generated by Django 3.1.7 on 2021-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img_works', models.ImageField(default='default.jpg', upload_to='pictures')),
                ('thumb_img', models.ImageField(default='default_thumb.jpg', upload_to='pictures')),
                ('client', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=40)),
            ],
        ),
    ]
