# Generated by Django 3.1.7 on 2021-03-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_works',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
