# Generated by Django 3.1.7 on 2021-05-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0002_others'),
    ]

    operations = [
        migrations.DeleteModel(
            name='others',
        ),
    ]
