# Generated by Django 3.1.7 on 2021-03-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0002_auto_20210327_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='our_works',
            new_name='our_work',
        ),
    ]
