# Generated by Django 3.1.7 on 2021-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0003_auto_20210327_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_work',
            old_name='post_images',
            new_name='img_works',
        ),
        migrations.AddField(
            model_name='our_work',
            name='thumb_img',
            field=models.ImageField(default='default_thumb.jpg', upload_to='pictures'),
        ),
    ]
