# Generated by Django 3.1.7 on 2021-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_main',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_other',
            field=models.ImageField(default='default.jpg', upload_to='pictures'),
        ),
    ]
