# Generated by Django 3.1.7 on 2021-03-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamnode', '0006_auto_20210331_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_main',
            field=models.TextField(default='There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it is a task to occupy the generations. And no matter how much progress one makes, there is always the thrill of just beginning.'),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_1',
            field=models.CharField(default='Heading', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_2',
            field=models.CharField(default='reaching for the stars', max_length=100),
        ),
    ]
